language: php

cache:
    directories:
        - ~/.cache/composer

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

matrix:
    fast_finish: true

install:
    - composer install $COMPOSERFLAGS

script:
    - vendor/bin/grumphp run
