language: php

cache:
  directories:
    - ~/.cache/composer

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer install

script:
  - vendor/bin/grumphp run
